# Build settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENCE.txt', 'CNAME']


# Site settings
title: GDG Akure
email: tomiwaijaware@gmail.com
description: "Sharing Technology. For Designers, Developers and Serious Tech Enthusiasts."
url: "http://akure.gdg.ng"
permalink: /blog/:title
googleAnalyticsTrackingId: ""
googleAnalyticsSiteUrl: ""

# Location block
eventLocationName: "Eco-innovation Hub"
eventLocationAddress: "No 3, Sam Olukayode Street, Alagbaka, Akure, Ondo State"
eventStartTime: "2014-10-18T10:00"
eventStartTimeHumanReadable: ""
eventEndTime: "2014-10-18T20:00"
eventEndTimeHumanReadable: ""
eventPlaceCoordinates: "7.24451, 5.22701"
mapCenterCoordinates: "7.24451, 5.22701"
mapMobileCenterCoordinates: "7.24451, 5.22701"

# Logistics Location Block
logisticsMapCenterCoordinates: "7.24451, 5.22701"
logisticsMapMobileCenterCoordinates: "7.24451, 5.22701"

#Tweets feed
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=900"

# Subscribe
subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"

# Documents for bscome a member
c4pUrl: "https://plus.google.com/u/0/communities/106484271764040223307"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, akure"
twitterAccount: "@GDGAkure"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Header
eventDate: "Sharing Technology. For Designers, Developers and Serious Tech Enthusiasts."
typeoutTextValues: '"", "Akure"'

# About Event Block
eventName: "GDG DevFest"

# Team Block
aboutUs: Google's services have become synonymous with simple things online. Number of technological innovations and IT industries in which Google is creating new products is enormous. It's hard to get to know all of them, but realistic. This is why people have started to gather in small local groups and share their experience. Later, the following groups have been called Google Developer Groups. GDGs can take many forms -- from just a few people getting together to watch some videos, to large gatherings with demos, tech talks, hackathons and conferences.

# Speakers List Block
showSessions: true
thumbnailsFolder: /img/communityManagers/

# Footer
gplusFollowUsUrl: "https://plus.google.com/communities/106484271764040223307"
twitterFollowUsUrl: "https://twitter.com/intent/user?screen_name=GDGAkure"
fbFollowUsUrl: "#"

# Blog
blogCommentsEnabled: true
discusShortName: "devfestua"
